### ISSUE TITLE
Bootloop

### ISSUE THREAD

**Issue by thehappydinoa** [paphonb/AndroidP-ify#1]
Made my phone get stuck in a boot loop. Essential PH-1 running 8.1.0.

**Comment by paphonb** [comment]
Logs please.

**Comment by thehappydinoa** [comment]
I had to wipe my boot img, how do I get logs before?

**Comment by wasdennnoch** [comment]
I guess you'll have to install it again ¯\_(ツ)_/¯

You don't have to do a full wipe, you can just delete the module via adb or flash the Xposed uninstaller (or magisk uninstaller).

**Comment by paphonb** [comment]
This will be closed as there is no more info provided.
