### ISSUE TITLE
Extra blank recent panel of pixel launcher 

### ISSUE THREAD

**Issue by abhishekgenius** [paphonb/AndroidP-ify#101]
I am currently using nitrogen os room on my redmi note 3. I use Android p-ify Xposed latest version i.e 1.0.0_50. I have opted for Android p like recent app panel. But whenever I open the recent panel there is unwanted, unopened blank pixel launcher recent card. When I open it nothing happens. If I kill it it reopens itself. Please provide a solution.

**Comment by paphonb** [comment]
My version of Pixel Launcher port will fix this.

**Comment by abhishekgenius** [comment]
Can I get the direct link
