### ISSUE TITLE
Please add option to remove small WiFi icon in QS

### ISSUE THREAD

**Issue by obipoketbobo** [paphonb/AndroidP-ify#104]
There's two now. Help.

**Comment by paphonb** [comment]
I don't understand what you mean. Maybe a screenshot?

**Comment by obipoketbobo** [comment]
May just be conflicting items from my ROM or Xposed.

**Comment by obipoketbobo** [comment]
Ah, just found out that it was part of the system UI tuner settings. Sorry
for disturbing you.
