### ISSUE TITLE
Empty space above QS

### ISSUE THREAD

**Issue by sumeshmeena** [paphonb/AndroidP-ify#11]
**Description**
There is empty space in the header region above QS after styling quick settings. Some people on xda forum suggested to change DPI but it's not working.

**Steps to reproduce**
1. Pull down status bar
2. Empty space above QS can be seen

**ROM info**
Moto G4 Plus - Resurrection Remix v6.0.0 [8.1.0_r15][athene][64-bit] | TWRP 64-bit | Magisk | Xposed Port by Magisk

**Module version (build version)**
AndroidPify-0.1.0_24.apk

**Logcat**
[logcat](https://forum.xda-developers.com/attachment.php?attachmentid=4451028&d=1521399675)

**Screenshots**
[1](https://forum.xda-developers.com/attachment.php?attachmentid=4451029&d=1521399855) [2](https://forum.xda-developers.com/attachment.php?attachmentid=4451030&d=1521399855)

**Comment by TimeRemnant9** [comment]
[com.android.systemui_2018.03.19_23.26.li.zip](https://github.com/paphonb/AndroidP-ify/files/1826343/com.android.systemui_2018.03.19_23.26.li.zip)

**Comment by paphonb** [comment]
Fixed in 45ed68e
