### ISSUE TITLE
Problem with QS icons on custom ROMs like AICP and AOSiP

### ISSUE THREAD

**Issue by RshBfn** [paphonb/AndroidP-ify#12]
**Description**

Have the same problem on AICP and AOSiP. The 6 QS icons on notification bar are way too down on AICP and way too up on AOSiP. and not padded equally. Also, the clock and date and battery and network icons, and some others are not in place and are pushed together in the centre I think. However, the QS icons are fine once the QS panel is expanded.

**Steps to reproduce**
1. Install AICP or AOSiP.
2. Pull down once to see the notification panel.

**ROM info**

Lenovo Z2 Plus on AICP and AOSiP.

**Module version (build version)**

All the versions upto the latest, 0.1.0_26.

**Screenshots**

From AICP,

![aicp1](https://user-images.githubusercontent.com/37551786/37613718-be7e8c48-2bce-11e8-8214-ae21dd0eb027.jpg)

![aicp2](https://user-images.githubusercontent.com/37551786/37613731-c61eba04-2bce-11e8-8045-fc3cd59c32f2.jpg)

From AOSiP,

![aosip](https://user-images.githubusercontent.com/37551786/37613696-b1bb69b8-2bce-11e8-8680-5a773fb8ebd9.jpg)

**Xposed log / logcat**

From AICP - [AICPerror.log](https://github.com/paphonb/AndroidP-ify/files/1826201/AICPerror.log)
From AOSiP - [AOSiPerror.log](https://github.com/paphonb/AndroidP-ify/files/1826203/AOSiPerror.log)

**Comment by sumeshmeena** [comment]
Remove comment syntax. i.e. `<!--     -->`

**Comment by RshBfn** [comment]
I know mate, I pressed the enter key without pressing shift and that messed it up.

**Comment by paphonb** [comment]
This should be fixed.
