### ISSUE TITLE
There is no icon for the suggestions from the settings, only a blue circle

### ISSUE THREAD

**Issue by xalexis2001** [paphonb/AndroidP-ify#14]
**Description**

In the settings, the "suggestions" icon at the very top of the screen shows as a blue circle instead of the proper icon, such as the "night mode is on" or "mobile data is off" warnings. However, when you hit the "expand" icon (which looks like some sort of arrow) the blue circles change to the usual correct icons, in this case, the "half-moon" and the "signal" icons. I will try to attach a few screenshots below, as pictures pretty much speak for themselves.
**Steps to reproduce**

**Module version (build version)**
         
Android P-ify 0.1.0 alpha #26

**Xposed log / logcat**
I don't think it will be needed

**Screenshots**

https://drive.google.com/file/d/1f0LCx-cR9lndajg5mX9_2WOmh32RQP_p/view?usp=drivesdk

https://drive.google.com/file/d/1MpIom1ViKGqLeIjb_JFe5bOVKT3obpgN/view?usp=drivesdk

**Comment by Jpkovas** [comment]
![screenshot_configuracoes_20180320-091903](https://user-images.githubusercontent.com/11709313/37655388-dd87dcac-2c23-11e8-9023-88983213ade2.png)

Lineage OS 15.1 Oneplus 5 has this issue too

**Comment by paphonb** [comment]
Fixed
