### ISSUE TITLE
Wrong color for search bar text in settings when using dark mode

### ISSUE THREAD

**Issue by Pieter-Dewachter** [paphonb/AndroidP-ify#15]
**Description**
When using dark mode, the text "Search Settings" is black, which makes it very hard to read on the dark settings theme. It looks fine when entering text, but the default text has the wrong color.

**Steps to reproduce**
1. Enable dark mode on the ROM and AndroidP-ify module.
2. Go to settings.
3. Notice the black text.

**ROM info**
AOSP 8.1 on OnePlus X (onyx)

**Module version (build version)**
Android P-ify snapshot 0.1.0 alpha #26

**Screenshot**
[1](https://imgur.com/a/PlIpv)

**Comment by Jpkovas** [comment]
Lineage OS 15.1 Oneplus 5 has this issue too.
![screenshot_configuracoes_20180320-091903](https://user-images.githubusercontent.com/11709313/37655434-0dc39230-2c24-11e8-923d-eaf8727c8b6d.png)

**Comment by paphonb** [comment]
Fixed in fa3f1cc.
