### ISSUE TITLE
Statusbar clock visible on lockscreen and ambient screen

### ISSUE THREAD

**Issue by Pieter-Dewachter** [paphonb/AndroidP-ify#16]
**Description**
The clock on the left of statusbar is visible on the lockscreen and on the ambient screen (black screen with clock when you hover screen). Normally this shouldn't be visible, since it is now interfering with the carrier text on the lockscreen and weird-looking on the ambient screen.

**Steps to reproduce**
1. Look to the statusbar on the lockscreen.
2. Look to the small clock (left-top corner) on the ambient screen.

**ROM info**
AOSP 8.1 on OnePlus X (onyx)

**Module version (build version)**
Android P-ify snapshot 0.1.0 alpha #26

**Screenshot**
[1](https://imgur.com/a/iwYai)

**Comment by bluehunter9** [comment]
I'm not experiencing this issue on the lockscreen nor ambient screen.
ROM info - LOS 15.1 HTC One M8
Module version - Android P-ify snapshot 0.1.0 alpha #26

**Comment by ElSaam** [comment]
Same problem. AOSiP 8.1 OnePlus 2. P-ify 0.1.0.

**Comment by paphonb** [comment]
AOSP doesn't have this issue. Please provide correct ROM info and both Xposed logs and logcat.

**Comment by luisbocanegra** [comment]
**Rom info**
AOSPExtended 5.3 android 8.1
**Logs**
[xposed_error_20180320_152853.log](https://github.com/paphonb/AndroidP-ify/files/1831298/xposed_error_20180320_152853.log)
[logcat.txt](https://github.com/paphonb/AndroidP-ify/files/1831308/logcat.txt)
**Screenshots**
![screenshot_gallery_20180320-154135](https://user-images.githubusercontent.com/15076387/37684389-79831e24-2c55-11e8-8b8b-3556726b932e.png)
![screenshot_gallery_20180320-154123](https://user-images.githubusercontent.com/15076387/37684391-7d4c6a10-2c55-11e8-8010-16e6d09c0a28.png)

**Comment by paphonb** [comment]
This issue is because of a conflict between your ROM's left clock and the module's left clock. Please disable left clock in the module settings.
