### ISSUE TITLE
Wrong colors of 4g/LTE, upload/download indicators in light theme

### ISSUE THREAD

**Issue by Jpkovas** [paphonb/AndroidP-ify#19]
Description:
The 4G/LTE indicators are black when using light theme, this should be white and the upload/download on both wifi and 4G are misplaced and in the wrong color too (black).

Steps to reproduce:

1. Use light theme
2. Pull down QS

ROM info:
Lineage OS 15.1 on Oneplus 5

Module version (build version):

Android P-ify version 0.1.0 alpha #26

Screenshot: 
![screenshot_tela_de_inicio_do_pixel_20180320-091923](https://user-images.githubusercontent.com/11709313/37656056-b75b7a0a-2c25-11e8-9fb6-a88a1ad3036b.png)

Xposedlog:
[xposed_error_20180320_095827.log](https://github.com/paphonb/AndroidP-ify/files/1829368/xposed_error_20180320_095827.log)

**Comment by RouNNdeL** [comment]
I have the same problem (OnePlus One Fabulous Oreo 8.1). Also the media Off status is not displayed properly (it shows a black cross next to the icon, but the background stays blue).
