### ISSUE TITLE
WIFI icon in settings is not themed + Preference Unreadable 

### ISSUE THREAD

**Issue by alexandrumarcel** [paphonb/AndroidP-ify#2]
So, the WIFI icon isn't themed and I get an error in the app menu "Preference Unreadable" 

https://imgur.com/ToeC48E

Edit: after I've checked the app again the error is gone, but the WiFi icon is still unthemed

**Comment by ja-som** [comment]
On my Nexus 5X with stock Oreo 8.1 it is the "Network & Internet" icon, also the "Support & tips" icon in settings is not themed, and icon for "Google" in settings is only blue circle.
No error in Xposed log.
![screenshot_20180318-010502](https://user-images.githubusercontent.com/5942380/37561215-44f28766-2a49-11e8-8db8-482b5ea1ef6e.png)

**Comment by Haxk20** [comment]
I can confirm this issue. No errors in xposed too.

**Comment by ja-som** [comment]
@Haxk20 update Android P-ify to the latest version, it was fixed.

**Comment by Haxk20** [comment]
@ja-som Yes i saw commit fixing this after i exited this issue forgot to wrote here. But Thank you.
