### ISSUE TITLE
Wrong cellular icon off state

### ISSUE THREAD

**Issue by RouNNdeL** [paphonb/AndroidP-ify#23]
**Description**

The cellular icon appears as on despite being off (colored background, white icon)

**Steps to reproduce**

1. Pull down QS panel
2. Turn off cellular connection

**ROM info**

AOSP 8.1 Fabulous Oreo Oneplus One

**Module version (build version)**

Android P-ify 0.1.0 alpha #33

**Xposed log / logcat**
No logs

**Screenshot**
![screenshot_20180322-110529](https://user-images.githubusercontent.com/22538735/37764391-e0e3252e-2dc1-11e8-8b44-3258f621d1af.png)

**Comment by paphonb** [comment]
The tile represents cellular state not cellular data state, so this behavior is expected.

**Comment by RouNNdeL** [comment]
Isn't it a bit useless? The tile toggles the data state so I'd expect it to display that state and not whether cellular network is available.

**Comment by paphonb** [comment]
You'll have to ask Google about that then. I will not modify the tile behavior.

**Comment by RouNNdeL** [comment]
Understandable
