### ISSUE TITLE
Statusbar Top The QS is Total Black

### ISSUE THREAD

**Issue by omarilzz** [paphonb/AndroidP-ify#24]
**Description**

in the notification shade the status bar is back all i can see is the clock in the middle but no battery icon
**Steps to reproduce**

Statusbar Top The QS is Total Black only clock is in the middle
**ROM info**

Bootleggers 8.1 AOSP (Xiaomi Redmi Note 4X)
**Module version (build version)**

Android P-ify Version 0.2.0_41
**Xposed log / logcat**

There is No Crashes

**Comment by paphonb** [comment]
The issue templates say you have to put Xposed logs if no crash happened.

**Comment by paphonb** [comment]
Closed as no long provided
