### ISSUE TITLE
The corners of the quick settings panel is not rounded enough

### ISSUE THREAD

**Issue by rishikeshbeura** [paphonb/AndroidP-ify#28]
Hey,
I am running on AEX 5.3 on my Xiaomi Redmi Note 4 and I am on Android P-ify version 0.2.0_40 build.
I noticed that the the corners of the quick settings panel are not rounded enough like Android P, so please take a look on that 😊

**Comment by paphonb** [comment]
It is already rounded in build 41.

**Comment by rishikeshbeura** [comment]
Sir, I can't find build #41 any where, I am on #40, will you please send
link ?

**Comment by sumeshmeena** [comment]
https://github.com/paphonb/AndroidP-ify/releases/download/0.2.0_41/AndroidPify-0.2.0_41.apk
