### ISSUE TITLE
Bugged icon on the top of the notification pannel

### ISSUE THREAD

**Issue by NikoFresh** [paphonb/AndroidP-ify#38]
### **Description** 
The icon of battery, hour, date are not showing.

### **Device** 
Xiaomi Redmi 3 Pro - ReOS (Android 8.1) - Android P-Ify 0.20.0_51

### **Logcat** 
(  332): -----------------
02-23 00:38:39.976 I/Xposed  (  332): Starting Xposed version 90.1-beta3 (Systemless), compiled for SDK 27
02-23 00:38:39.976 I/Xposed  (  332): Device: Redmi 3 (Xiaomi), Android version 8.1.0 (SDK 27)
02-23 00:38:39.976 I/Xposed  (  332): ROM: re_ido-userdebug 8.1.0 OPM1.171019.019 666b16af33 test-keys
02-23 00:38:39.976 I/Xposed  (  332): Build fingerprint: Xiaomi/ido/ido:5.1.1/LMY47V/V9.2.1.0.LAIMIEK:user/release-keys
02-23 00:38:39.976 I/Xposed  (  332): Platform: arm64-v8a, 64-bit binary, system server: yes
02-23 00:38:39.976 I/Xposed  (  332): SELinux enabled: yes, enforcing: no
02-23 00:38:41.783 I/Xposed  (  332): -----------------
02-23 00:38:41.783 I/Xposed  (  332): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
02-23 00:38:44.970 I/Xposed  (  332): Detected ART runtime
02-23 00:38:44.972 I/Xposed  (  332): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
02-23 00:38:45.660 I/Xposed  (  332): Loading modules from /data/app/xyz.paphonb.androidpify-DXgdF07euiWXYu_BNRWwjg==/base.apk
02-23 00:38:45.984 I/Xposed  (  332):   Loading class xyz.paphonb.androidpify.XposedHook
02-23 00:38:49.034 I/Xposed  (  333): -----------------
02-23 00:38:49.035 I/Xposed  (  333): Starting Xposed version 90.1-beta3 (Systemless), compiled for SDK 27
02-23 00:38:49.035 I/Xposed  (  333): Device: Redmi 3 (Xiaomi), Android version 8.1.0 (SDK 27)
02-23 00:38:49.035 I/Xposed  (  333): ROM: re_ido-userdebug 8.1.0 OPM1.171019.019 666b16af33 test-keys
02-23 00:38:49.035 I/Xposed  (  333): Build fingerprint: Xiaomi/ido/ido:5.1.1/LMY47V/V9.2.1.0.LAIMIEK:user/release-keys
02-23 00:38:49.035 I/Xposed  (  333): Platform: arm64-v8a, 32-bit binary, system server: no
02-23 00:38:49.035 I/Xposed  (  333): SELinux enabled: yes, enforcing: no
02-23 00:38:51.654 I/Xposed  (  333): -----------------
02-23 00:38:51.654 I/Xposed  (  333): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
02-23 00:38:53.489 I/Xposed  (  333): Detected ART runtime
02-23 00:38:53.491 I/Xposed  (  333): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
02-23 00:38:54.014 I/Xposed  (  333): Loading modules from /data/app/xyz.paphonb.androidpify-DXgdF07euiWXYu_BNRWwjg==/base.apk
02-23 00:38:54.313 I/Xposed  (  333):   Loading class xyz.paphonb.androidpify.XposedHook
04-21 20:34:27.516 E/Xposed  ( 6094): java.lang.IllegalArgumentException: Cannot add a null child view to a ViewGroup
04-21 20:34:27.516 E/Xposed  ( 6094): 	at android.view.ViewGroup.addView(ViewGroup.java:4699)
04-21 20:34:27.516 E/Xposed  ( 6094): 	at xyz.paphonb.androidpify.hooks.QuickSettingsHook$handleLoadPackage$3.afterHookedMethod(QuickSettingsHook.kt:246)
04-21 20:34:27.516 E/Xposed  ( 6094): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:375)
04-21 20:34:27.516 E/Xposed  ( 6094): 	at com.android.systemui.qs.QuickStatusBarHeader.onFinishInflate(<Xposed>)
04-21 20:34:27.516 E/Xposed  ( 6094): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:876)
04-21 20:34:27.516 E/Xposed  ( 6094): 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
04-21 20:34:27.516 E/Xposed  ( 6094): 	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:995)
04-21 20:34:27.516 E/Xposed  ( 6094): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
04-21 20:34:27.516 E/Xposed  ( 6094): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:361)
04-21 20:34:27.516 E/Xposed  ( 6094): 	at android.view.LayoutInflater.parseInclude(<Xposed>)
04-21 20:34:27.516 E/Xposed  ( 6094): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:859)
04-21 20:34:27.516 E/Xposed  ( 6094): 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
04-21 20:34:27.516 E/Xposed  ( 6094): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
04-21 20:34:27.516 E/Xposed  ( 6094): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
04-21 20:34:27.516 E/Xposed  ( 6094): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:361)
04-21 20:34:27.516 E/Xposed  ( 6094): 	at android.view.LayoutInflater.inflate(<Xposed>)
04-21 20:34:27.516 E/Xposed  ( 6094): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
04-21 20:34:27.516 E/Xposed  ( 6094): 	at com.android.systemui.qs.QSFragment.onCreateView(QSFragment.java:78)
04-21 20:34:27.516 E/Xposed  ( 6094): 	at android.app.Fragment.performCreateView(Fragment.java:2508)
04-21 20:34:27.516 E/Xposed  ( 6094): 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1279)
04-21 20:34:27.516 E/Xposed  ( 6094): 	at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2407)
04-21 20:34:27.516 E/Xposed  ( 6094): 	at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2186)
04-21 20:34:27.516 E/Xposed  ( 6094): 	at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2142)
04-21 20:34:27.516 E/Xposed  ( 6094): 	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2043)
04-21 20:34:27.516 E/Xposed  ( 6094): 	at android.app.FragmentManagerImpl$1.run(FragmentManager.java:719)
04-21 20:34:27.516 E/Xposed  ( 6094): 	at android.os.Handler.handleCallback(Handler.java:790)
04-21 20:34:27.516 E/Xposed  ( 6094): 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-21 20:34:27.516 E/Xposed  ( 6094): 	at android.os.Looper.loop(Looper.java:164)
04-21 20:34:27.516 E/Xposed  ( 6094): 	at android.app.ActivityThread.main(ActivityThread.java:6523)
04-21 20:34:27.516 E/Xposed  ( 6094): 	at java.lang.reflect.Method.invoke(Native Method)
04-21 20:34:27.516 E/Xposed  ( 6094): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
04-21 20:34:27.516 E/Xposed  ( 6094): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
04-21 20:34:27.516 E/Xposed  ( 6094): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)
04-21 20:34:27.625 E/Xposed  ( 6094): java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.ViewGroup.addView(android.view.View, int)' on a null object reference
04-21 20:34:27.625 E/Xposed  ( 6094): 	at xyz.paphonb.androidpify.hooks.QuickSettingsHook$handleLoadPackage$1.afterHookedMethod(QuickSettingsHook.kt:189)
04-21 20:34:27.625 E/Xposed  ( 6094): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:375)
04-21 20:34:27.625 E/Xposed  ( 6094): 	at com.android.systemui.qs.QSContainerImpl.onFinishInflate(<Xposed>)
04-21 20:34:27.625 E/Xposed  ( 6094): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:876)
04-21 20:34:27.625 E/Xposed  ( 6094): 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
04-21 20:34:27.625 E/Xposed  ( 6094): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
04-21 20:34:27.625 E/Xposed  ( 6094): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
04-21 20:34:27.625 E/Xposed  ( 6094): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:361)
04-21 20:34:27.625 E/Xposed  ( 6094): 	at android.view.LayoutInflater.inflate(<Xposed>)
04-21 20:34:27.625 E/Xposed  ( 6094): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
04-21 20:34:27.625 E/Xposed  ( 6094): 	at com.android.systemui.qs.QSFragment.onCreateView(QSFragment.java:78)
04-21 20:34:27.625 E/Xposed  ( 6094): 	at android.app.Fragment.performCreateView(Fragment.java:2508)
04-21 20:34:27.625 E/Xposed  ( 6094): 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1279)
04-21 20:34:27.625 E/Xposed  ( 6094): 	at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2407)
04-21 20:34:27.625 E/Xposed  ( 6094): 	at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2186)
04-21 20:34:27.625 E/Xposed  ( 6094): 	at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2142)
04-21 20:34:27.625 E/Xposed  ( 6094): 	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2043)
04-21 20:34:27.625 E/Xposed  ( 6094): 	at android.app.FragmentManagerImpl$1.run(FragmentManager.java:719)
04-21 20:34:27.625 E/Xposed  ( 6094): 	at android.os.Handler.handleCallback(Handler.java:790)
04-21 20:34:27.625 E/Xposed  ( 6094): 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-21 20:34:27.625 E/Xposed  ( 6094): 	at android.os.Looper.loop(Looper.java:164)
04-21 20:34:27.625 E/Xposed  ( 6094): 	at android.app.ActivityThread.main(ActivityThread.java:6523)
04-21 20:34:27.625 E/Xposed  ( 6094): 	at java.lang.reflect.Method.invoke(Native Method)
04-21 20:34:27.625 E/Xposed  ( 6094): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
04-21 20:34:27.625 E/Xposed  ( 6094): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
04-21 20:34:27.625 E/Xposed  ( 6094): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)
04-21 20:34:27.630 I/Xposed  ( 6094): [Android P-ify] [ERROR] : onAttachedToWindow: mIconManager = null

**Comment by paphonb** [comment]
This should be fixed.
