### ISSUE TITLE
Can't run .41 up to .60

### ISSUE THREAD

**Issue by heichi13** [paphonb/AndroidP-ify#43]
**Description**

I was running .40, cleared the data and cache of the app and installed .60. I've tried this since .41. Booted up with black screen after the boot animation.

**Steps to reproduce**

1. Install app
2. Reboot via Xposed
3. Boots black screen after boot animation

**ROM info**

OmniROM 8.0 on Oppo Find7 (X9076)

**Module version (build version)**

AndroidPify-0.2.0_60

**Xposed log / logcat**

[Dropbox link](https://www.dropbox.com/s/tb4whwrbocf6fnn/logcat.txt?dl=0)

**Comment by paphonb** [comment]
Does it work on newer versions?

**Comment by heichi13** [comment]
I have since updated to 8.1.
