### ISSUE TITLE
the recent menu animation doesn't work and pixel launcher appears in recent

### ISSUE THREAD

**Issue by Bebarse** [paphonb/AndroidP-ify#62]
**Description**
when you are in app and want to go to recent menu the animation doesn't work and the pixel launcher appears in the menu weirdly

**Steps to reproduce**

**ROM info**

**Module version (build version)**

**Xposed log / logcat**
no logcat

**Comment by paphonb** [comment]
The animations won't be fixed because it requires new classes that aren't available in Oreo.

**Comment by abhishekgenius** [comment]
Use pixel launcher provided by paphonb
