### ISSUE TITLE
New recents not working

### ISSUE THREAD

**Issue by Deven990** [paphonb/AndroidP-ify#69]
Rom : Pixel Experience 8.1.0 

Device : Yu Yuphoria ( lettuce )

Module : 1.0.0-116
 

 Log : 05-12 17:40:50.093 I/Xposed  (19268): -----------------

05-12 17:40:50.093 I/Xposed  (19268): Starting Xposed version 90.2-beta3 (Systemless), compiled for SDK 27

05-12 17:40:50.093 I/Xposed  (19268): Device: YU5010 (YU), Android version 8.1.0 (SDK 27)

05-12 17:40:50.093 I/Xposed  (19268): ROM: OPM1.171019.018

05-12 17:40:50.093 I/Xposed  (19268): Build fingerprint: YU/YUPHORIA/YUPHORIA:5.1.1/LMY49J/YOG4PAS8A8:user/release-keys

05-12 17:40:50.093 I/Xposed  (19268): Platform: arm64-v8a, 64-bit binary, system server: yes

05-12 17:40:50.093 I/Xposed  (19268): SELinux enabled: yes, enforcing: no

05-12 17:40:52.912 I/Xposed  (19268): -----------------

05-12 17:40:52.912 I/Xposed  (19268): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH

05-12 17:40:55.310 I/Xposed  (19268): Detected ART runtime

05-12 17:40:55.312 I/Xposed  (19268): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing

05-12 17:40:55.609 I/Xposed  (19268): Loading modules from /data/app/xyz.paphonb.androidpify-xX8V3xtMy11jQ7DdwEdoyw==/base.apk

05-12 17:40:55.995 I/Xposed  (19268):   Loading class xyz.paphonb.androidpify.XposedHook

05-12 17:41:09.309 I/Xposed  (19631): [Android P-ify] [ERROR] : onAttachedToWindow: mIconManager = null

**Comment by paphonb** [comment]
This feature is not supported.
