### ISSUE TITLE
[REQUEST] Please exclude all kinds of launchers from the new recents

### ISSUE THREAD

**Issue by jahirfiquitiva** [paphonb/AndroidP-ify#70]

**Comment by paphonb** [comment]
This feature is not supported.

**Comment by jahirfiquitiva** [comment]
May I know why it isn't supported?

**Comment by paphonb** [comment]
Because I just did it as an experiment. I have no intention to fix anything related to that.

**Comment by jahirfiquitiva** [comment]
Oh ok. Thanks for the info @paphonb :smile:
