### ISSUE TITLE
Lockscreen have weird clock bug

### ISSUE THREAD

**Issue by cptmacp** [paphonb/AndroidP-ify#75]
**Description**
Lockscreen have a weird Box on it near the time. 

**Steps to reproduce**

Lockscreen have it .
lockscreen clock 

**ROM info**

Lineage OS 15.1 Nightly For oneplus 2

**Module version (build version)**

Android P-ify snapshot 1.0.0_116

**Xposed log / logcat**

[xposed_error_20180513_105515.log](https://github.com/paphonb/AndroidP-ify/files/1998157/xposed_error_20180513_105515.log)

**Screenshot for the error*

[screenshot_pixel_launcher_20180513-104408](https://user-images.githubusercontent.com/11556463/39964187-4f1d60a6-569c-11e8-87ce-c103f49501e9.png)

**Comment by codehz** [comment]
@cptmacp 

You can use adb to get screenshot 
```
adb shell screencap -p /sdcard/screen.png
adb pull -p -a /sdcard/screen.png
adb shell rm /sdcard/screen.png
```

**Comment by paphonb** [comment]
This happens when you have custom fonts set. It can be fixed by disabling Google Sans in module config.

**Comment by Tahir03000** [comment]
How to disable Google sans in module?
