### ISSUE TITLE
Black Screen on firehound rom

### ISSUE THREAD

**Issue by vpeace** [paphonb/AndroidP-ify#76]
**Description**
After installing the module and rebooting the phone, the screen stays black. I'm sorry I can't produce an xposed log since I have to reflash the rom to make it work again
**Steps to reproduce**
Flash Firehound V4.5 and latest version of P-ify
**ROM info**
FireHound v4.5 on nexus6p
**Module version (build version)**
 Android P-ify version 0.1.0 alpha88

**Comment by paphonb** [comment]
No logs provided.

**Comment by vpeace** [comment]
I'm not able to capture logs
