### ISSUE TITLE
Extra Space between QS tiles 

### ISSUE THREAD

**Issue by ASP2** [paphonb/AndroidP-ify#8]
**Description**

**Steps to reproduce**

**ROM info**

**Module version (build version)**

**Xposed log / logcat**
01-09 09:51:30.473 I/Xposed  (  683): -----------------
01-09 09:51:30.473 I/Xposed  (  683): Starting Xposed version 90.1-beta3 (Systemless), compiled for SDK 27
01-09 09:51:30.473 I/Xposed  (  683): Device: Lenovo P2 (Lenovo), Android version 8.1.0 (SDK 27)
01-09 09:51:30.473 I/Xposed  (  683): ROM: aosip_kuntao-userdebug 8.1.0 OPM1.171019.021 8f6589c583 test-keys
01-09 09:51:30.473 I/Xposed  (  683): Build fingerprint: Lenovo/kuntao_row/P2a42:7.0/NRD90N/P2a42_S244_170725_ROW:user/release-keys
01-09 09:51:30.473 I/Xposed  (  683): Platform: arm64-v8a, 64-bit binary, system server: yes
01-09 09:51:30.473 I/Xposed  (  683): SELinux enabled: yes, enforcing: no
01-09 09:51:34.415 I/Xposed  (  683): -----------------
01-09 09:51:34.415 I/Xposed  (  683): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
03-19 22:07:42.456 I/Xposed  (  683): Detected ART runtime
03-19 22:07:42.458 I/Xposed  (  683): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
03-19 22:07:42.885 I/Xposed  (  683): Loading modules from /data/app/xyz.paphonb.androidpify-5mo5asoorB8WwMksDOVFlQ==/base.apk
03-19 22:07:43.179 I/Xposed  (  683):   Loading class xyz.paphonb.androidpify.XposedHook
03-19 22:07:46.485 I/Xposed  (  684): -----------------
03-19 22:07:46.485 I/Xposed  (  684): Starting Xposed version 90.1-beta3 (Systemless), compiled for SDK 27
03-19 22:07:46.485 I/Xposed  (  684): Device: Lenovo P2 (Lenovo), Android version 8.1.0 (SDK 27)
03-19 22:07:46.485 I/Xposed  (  684): ROM: aosip_kuntao-userdebug 8.1.0 OPM1.171019.021 8f6589c583 test-keys
03-19 22:07:46.485 I/Xposed  (  684): Build fingerprint: Lenovo/kuntao_row/P2a42:7.0/NRD90N/P2a42_S244_170725_ROW:user/release-keys
03-19 22:07:46.485 I/Xposed  (  684): Platform: arm64-v8a, 32-bit binary, system server: no
03-19 22:07:46.485 I/Xposed  (  684): SELinux enabled: yes, enforcing: no
03-19 22:07:49.731 I/Xposed  (  684): -----------------
03-19 22:07:49.731 I/Xposed  (  684): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
03-19 22:07:51.111 I/Xposed  (  684): Detected ART runtime
03-19 22:07:51.115 I/Xposed  (  684): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
03-19 22:07:51.444 I/Xposed  (  684): Loading modules from /data/app/xyz.paphonb.androidpify-5mo5asoorB8WwMksDOVFlQ==/base.apk
03-19 22:07:53.469 I/Xposed  (  684):   Loading class xyz.paphonb.androidpify.XposedHook
03-19 22:08:11.446 I/Xposed  ( 1637): [Android P-ify] [ERROR] : onAttachedToWindow: mIconManager = null

**Comment by paphonb** [comment]
No screenshots describing the problem.

**Comment by paphonb** [comment]
Fixed in 45ed68e.
