### ISSUE TITLE
SystemUI crashes randomly sometimes

### ISSUE THREAD

**Issue by frknkrc44** [paphonb/AndroidP-ify#90]
**Description**
SystemUI crashes randomly sometimes

**Steps to reproduce**
Crashes randomly without do any process

**ROM info**
Resurrection Remix 6.0.0 on LG G3 (D855)

**Module version (build version)**
Android P-ify version 1.0.0 build 146

**Xposed log / logcat**
android.content.res.Resources$NotFoundException: Resource ID #0x105010a type #0x3 is not valid
    at android.content.res.Resources.getDimensionPixelSize(Resources.java:723)
    at android.content.res.XResources.getDimensionPixelSize(XResources.java:741)
    at com.android.internal.widget.ImageFloatingTextView.makeSingleLayout(ImageFloatingTextView.java:100)
    at android.widget.TextView.makeNewLayout(TextView.java:7853)
    at android.widget.TextView.checkForRelayout(TextView.java:8500)
    at android.widget.TextView.setHint(TextView.java:5539)
    at com.android.internal.widget.ImageFloatingTextView.setNumIndentLines(ImageFloatingTextView.java:173)
    at com.android.internal.widget.MessagingLinearLayout.onMeasure(MessagingLinearLayout.java:176)
    at android.view.View.measure(View.java:22091)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
    at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
    at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
    at android.view.View.measure(View.java:22091)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
    at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
    at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
    at android.view.View.measure(View.java:22091)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
    at android.view.View.measure(View.java:22091)
    at com.android.systemui.statusbar.NotificationContentView.onMeasure(NotificationContentView.java:181)
    at android.view.View.measure(View.java:22091)
    at com.android.systemui.statusbar.ExpandableView.onMeasure(ExpandableView.java:82)
    at android.view.View.measure(View.java:22091)
    at com.android.systemui.statusbar.stack.NotificationChildrenContainer.onMeasure(NotificationChildrenContainer.java:207)
    at android.view.View.measure(View.java:22091)
    at com.android.systemui.statusbar.ExpandableView.onMeasure(ExpandableView.java:82)
    at android.view.View.measure(View.java:22091)
    at android.view.ViewGroup.measureChild(ViewGroup.java:6573)
    at com.android.systemui.statusbar.stack.NotificationStackScrollLayout.onMeasure(NotificationStackScrollLayout.java:556)
    at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:361)
    at com.android.systemui.statusbar.stack.NotificationStackScrollLayout.onMeasure(<Xposed>)
    at android.view.View.measure(View.java:22091)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
    at android.view.View.measure(View.java:22091)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
    at android.view.View.measure(View.java:22091)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
    at android.view.View.measure(View.java:22091)
    at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2437)
    at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1519)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1776)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1407)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6783)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
    at android.view.Choreographer.doCallbacks(Choreographer.java:723)
    at android.view.Choreographer.doFrame(Choreographer.java:658)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
    at android.os.Handler.handleCallback(Handler.java:790)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6499)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)

**Comment by paphonb** [comment]
That is not caused by this module. Please check if you have any other Xposed modules or substratum themes.

**Comment by frknkrc44** [comment]
I has new Xposed log includes your module's error today, my log is:
05-19 14:57:29.634 I/Xposed  ( 8099): [Android P-ify] [ERROR] : onAttachedToWindow: mIconManager = null
05-19 14:57:32.462 E/Xposed  ( 8099): de.robv.android.xposed.XposedHelpers$InvocationTargetError: android.content.res.Resources$NotFoundException: Resource ID #0x105010a type #0x12 is not valid
05-19 14:57:32.462 E/Xposed  ( 8099): 	at de.robv.android.xposed.XposedHelpers.callMethod(XposedHelpers.java:1271)
05-19 14:57:32.462 E/Xposed  ( 8099): 	at xyz.paphonb.androidpify.hooks.NotificationStackHook$handleLoadPackage$4.afterHookedMethod(NotificationStackHook.kt:185)
05-19 14:57:32.462 E/Xposed  ( 8099): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:375)
05-19 14:57:32.462 E/Xposed  ( 8099): 	at com.android.systemui.statusbar.stack.NotificationStackScrollLayout.onMeasure(<Xposed>)
05-19 14:57:32.462 E/Xposed  ( 8099): 	at android.view.View.measure(View.java:22091)
05-19 14:57:32.462 E/Xposed  ( 8099): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
05-19 14:57:32.462 E/Xposed  ( 8099): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
05-19 14:57:32.462 E/Xposed  ( 8099): 	at android.view.View.measure(View.java:22091)
05-19 14:57:32.462 E/Xposed  ( 8099): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
05-19 14:57:32.462 E/Xposed  ( 8099): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
05-19 14:57:32.462 E/Xposed  ( 8099): 	at android.view.View.measure(View.java:22091)
05-19 14:57:32.462 E/Xposed  ( 8099): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
05-19 14:57:32.462 E/Xposed  ( 8099): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
05-19 14:57:32.462 E/Xposed  ( 8099): 	at android.view.View.measure(View.java:22091)
05-19 14:57:32.462 E/Xposed  ( 8099): 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2437)
05-19 14:57:32.462 E/Xposed  ( 8099): 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1519)
05-19 14:57:32.462 E/Xposed  ( 8099): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1776)
05-19 14:57:32.462 E/Xposed  ( 8099): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1407)
05-19 14:57:32.462 E/Xposed  ( 8099): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6783)
05-19 14:57:32.462 E/Xposed  ( 8099): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
05-19 14:57:32.462 E/Xposed  ( 8099): 	at android.view.Choreographer.doCallbacks(Choreographer.java:723)
05-19 14:57:32.462 E/Xposed  ( 8099): 	at android.view.Choreographer.doFrame(Choreographer.java:658)
05-19 14:57:32.462 E/Xposed  ( 8099): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
05-19 14:57:32.462 E/Xposed  ( 8099): 	at android.os.Handler.handleCallback(Handler.java:790)
05-19 14:57:32.462 E/Xposed  ( 8099): 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-19 14:57:32.462 E/Xposed  ( 8099): 	at android.os.Looper.loop(Looper.java:164)
05-19 14:57:32.462 E/Xposed  ( 8099): 	at android.app.ActivityThread.main(ActivityThread.java:6499)
05-19 14:57:32.462 E/Xposed  ( 8099): 	at java.lang.reflect.Method.invoke(Native Method)
05-19 14:57:32.462 E/Xposed  ( 8099): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
05-19 14:57:32.462 E/Xposed  ( 8099): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
05-19 14:57:32.462 E/Xposed  ( 8099): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)
05-19 14:57:32.462 E/Xposed  ( 8099): Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x105010a type #0x12 is not valid
05-19 14:57:32.462 E/Xposed  ( 8099): 	at android.content.res.Resources.getDimensionPixelSize(Resources.java:723)
05-19 14:57:32.462 E/Xposed  ( 8099): 	at android.content.res.XResources.getDimensionPixelSize(XResources.java:741)
05-19 14:57:32.462 E/Xposed  ( 8099): 	at com.android.internal.widget.ImageFloatingTextView.makeSingleLayout(ImageFloatingTextView.java:100)
05-19 14:57:32.462 E/Xposed  ( 8099): 	at android.widget.TextView.makeNewLayout(TextView.java:7853)
05-19 14:57:32.462 E/Xposed  ( 8099): 	at android.widget.TextView.onMeasure(TextView.java:8210)
05-19 14:57:32.462 E/Xposed  ( 8099): 	at com.android.internal.widget.ImageFloatingTextView.onMeasure(ImageFloatingTextView.java:137)
05-19 14:57:32.462 E/Xposed  ( 8099): 	at android.view.View.measure(View.java:22091)
05-19 14:57:32.462 E/Xposed  ( 8099): 	at com.android.internal.widget.MessagingLinearLayout.onMeasure(MessagingLinearLayout.java:186)
05-19 14:57:32.462 E/Xposed  ( 8099): 	at android.view.View.measure(View.java:22091)
05-19 14:57:32.462 E/Xposed  ( 8099): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
05-19 14:57:32.462 E/Xposed  ( 8099): 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
05-19 14:57:32.462 E/Xposed  ( 8099): 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
05-19 14:57:32.462 E/Xposed  ( 8099): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
05-19 14:57:32.462 E/Xposed  ( 8099): 	at android.view.View.measure(View.java:22091)
05-19 14:57:32.462 E/Xposed  ( 8099): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
05-19 14:57:32.462 E/Xposed  ( 8099): 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
05-19 14:57:32.462 E/Xposed  ( 8099): 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
05-19 14:57:32.462 E/Xposed  ( 8099): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
05-19 14:57:32.462 E/Xposed  ( 8099): 	at android.view.View.measure(View.java:22091)
05-19 14:57:32.462 E/Xposed  ( 8099): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
05-19 14:57:32.462 E/Xposed  ( 8099): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
05-19 14:57:32.462 E/Xposed  ( 8099): 	at android.view.View.measure(View.java:22091)
05-19 14:57:32.462 E/Xposed  ( 8099): 	at com.android.systemui.statusbar.NotificationContentView.onMeasure(NotificationContentView.java:181)
05-19 14:57:32.462 E/Xposed  ( 8099): 	at android.view.View.measure(View.java:22091)
05-19 14:57:32.462 E/Xposed  ( 8099): 	at com.android.systemui.status
05-19 14:57:32.711 E/Xposed  ( 8099): de.robv.android.xposed.XposedHelpers$InvocationTargetError: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.text.Layout.getHeight()' on a null object reference
05-19 14:57:32.711 E/Xposed  ( 8099): 	at de.robv.android.xposed.XposedHelpers.callMethod(XposedHelpers.java:1271)
05-19 14:57:32.711 E/Xposed  ( 8099): 	at xyz.paphonb.androidpify.hooks.NotificationStackHook$handleLoadPackage$4.afterHookedMethod(NotificationStackHook.kt:185)
05-19 14:57:32.711 E/Xposed  ( 8099): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:375)
05-19 14:57:32.711 E/Xposed  ( 8099): 	at com.android.systemui.statusbar.stack.NotificationStackScrollLayout.onMeasure(<Xposed>)
05-19 14:57:32.711 E/Xposed  ( 8099): 	at android.view.View.measure(View.java:22091)
05-19 14:57:32.711 E/Xposed  ( 8099): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
05-19 14:57:32.711 E/Xposed  ( 8099): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
05-19 14:57:32.711 E/Xposed  ( 8099): 	at android.view.View.measure(View.java:22091)
05-19 14:57:32.711 E/Xposed  ( 8099): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
05-19 14:57:32.711 E/Xposed  ( 8099): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
05-19 14:57:32.711 E/Xposed  ( 8099): 	at android.view.View.measure(View.java:22091)
05-19 14:57:32.711 E/Xposed  ( 8099): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
05-19 14:57:32.711 E/Xposed  ( 8099): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
05-19 14:57:32.711 E/Xposed  ( 8099): 	at android.view.View.measure(View.java:22091)
05-19 14:57:32.711 E/Xposed  ( 8099): 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2437)
05-19 14:57:32.711 E/Xposed  ( 8099): 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1519)
05-19 14:57:32.711 E/Xposed  ( 8099): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1776)
05-19 14:57:32.711 E/Xposed  ( 8099): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1407)
05-19 14:57:32.711 E/Xposed  ( 8099): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6783)
05-19 14:57:32.711 E/Xposed  ( 8099): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
05-19 14:57:32.711 E/Xposed  ( 8099): 	at android.view.Choreographer.doCallbacks(Choreographer.java:723)
05-19 14:57:32.711 E/Xposed  ( 8099): 	at android.view.Choreographer.doFrame(Choreographer.java:658)
05-19 14:57:32.711 E/Xposed  ( 8099): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
05-19 14:57:32.711 E/Xposed  ( 8099): 	at android.os.Handler.handleCallback(Handler.java:790)
05-19 14:57:32.711 E/Xposed  ( 8099): 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-19 14:57:32.711 E/Xposed  ( 8099): 	at android.os.Looper.loop(Looper.java:164)
05-19 14:57:32.711 E/Xposed  ( 8099): 	at android.app.ActivityThread.main(ActivityThread.java:6499)
05-19 14:57:32.711 E/Xposed  ( 8099): 	at java.lang.reflect.Method.invoke(Native Method)
05-19 14:57:32.711 E/Xposed  ( 8099): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
05-19 14:57:32.711 E/Xposed  ( 8099): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
05-19 14:57:32.711 E/Xposed  ( 8099): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)
05-19 14:57:32.711 E/Xposed  ( 8099): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.text.Layout.getHeight()' on a null object reference
05-19 14:57:32.711 E/Xposed  ( 8099): 	at com.android.internal.widget.ImageFloatingTextView.getLayoutHeight(ImageFloatingTextView.java:180)
05-19 14:57:32.711 E/Xposed  ( 8099): 	at com.android.internal.widget.MessagingLinearLayout.onMeasure(MessagingLinearLayout.java:141)
05-19 14:57:32.711 E/Xposed  ( 8099): 	at android.view.View.measure(View.java:22091)
05-19 14:57:32.711 E/Xposed  ( 8099): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
05-19 14:57:32.711 E/Xposed  ( 8099): 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
05-19 14:57:32.711 E/Xposed  ( 8099): 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
05-19 14:57:32.711 E/Xposed  ( 8099): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
05-19 14:57:32.711 E/Xposed  ( 8099): 	at android.view.View.measure(View.java:22091)
05-19 14:57:32.711 E/Xposed  ( 8099): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
05-19 14:57:32.711 E/Xposed  ( 8099): 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
05-19 14:57:32.711 E/Xposed  ( 8099): 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
05-19 14:57:32.711 E/Xposed  ( 8099): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
05-19 14:57:32.711 E/Xposed  ( 8099): 	at android.view.View.measure(View.java:22091)
05-19 14:57:32.711 E/Xposed  ( 8099): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
05-19 14:57:32.711 E/Xposed  ( 8099): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
05-19 14:57:32.711 E/Xposed  ( 8099): 	at android.view.View.measure(View.java:22091)
05-19 14:57:32.711 E/Xposed  ( 8099): 	at com.android.systemui.statusbar.NotificationContentView.onMeasure(NotificationContentView.java:181)
05-19 14:57:32.711 E/Xposed  ( 8099): 	at android.view.View.measure(View.java:22091)
05-19 14:57:32.711 E/Xposed  ( 8099): 	at com.android.systemui.statusbar.ExpandableView.onMeasure(ExpandableView.java:82)
05-19 14:57:32.711 E/Xposed  ( 8099): 	at android.view.View.measure(View.java:22091)
05-19 14:57:32.711 E/Xposed  ( 8099): 	at android.view.ViewGroup.measureChild(ViewGroup.java:6573)
05-19 14:57:32.711 E/Xposed  ( 8099): 	at java.lang.reflect.Method.invoke(Native Method)
05-19 14:57:32.711 E/Xposed  ( 8099): 	at de.robv.android.xposed.XposedHelpers.callMethod(XposedHelpers.java:1263)
05-19 14:57:32.711 E/Xposed  ( 8099): 	... 30 more

**Comment by paphonb** [comment]
My module is just bridging unrelated API calls in this case. Still not the cause.
