### ISSUE TITLE
Opening recents from within an app breaks the animation until restart

### ISSUE THREAD

**Issue by XeZrunner** [paphonb/AndroidP-ify#93]
**Description**
Entering the new recents panel from the home screen gives a nice animation back and forth. Entering the recents panel from an app though, the app slides down, and the recents just appears. **From this point onwards, the recents panel, even from the home screen, simply fades in and out, instead of the nice slide up animation on the home screen.**

**Steps to reproduce**
(on a clean boot)
1. Open and close app switcher from homescreen, and observe the animation.
2. Open an app.
3. Now, without closing the app, open the app switcher and observe the animation.
4. Go back to the homescreen, open and close the app switcher, and observe the animation.

**ROM info**
**Cardinal-AOSP 5.5** on **Xiaomi Redmi Note 4** Global (**Android 8.1.0** Oreo) + FrancoKernel

**Module version (build version)**
Android P-ify version 1.0.0 \#148

**Video showcasing the issue**
[YouTube link](https://www.youtube.com/watch?v=TNw2X1FtNnI)

**Xposed log / logcat**
```
05-22 14:05:30.870 I/Xposed  ( 7652): -----------------
05-22 14:05:30.870 I/Xposed  ( 7652): Starting Xposed version 90.2-beta3 (Systemless), compiled for SDK 27
05-22 14:05:30.870 I/Xposed  ( 7652): Device: Redmi Note 4 (Xiaomi), Android version 8.1.0 (SDK 27)
05-22 14:05:30.870 I/Xposed  ( 7652): ROM: cardinal_mido-userdebug 8.1.0 OPM2.171019.029 0b09109e8f release-keys
05-22 14:05:30.870 I/Xposed  ( 7652): Build fingerprint: xiaomi/mido/mido:7.0/NRD90M/V8.5.4.0.NCFMIED:user/release-keys
05-22 14:05:30.870 I/Xposed  ( 7652): Platform: arm64-v8a, 64-bit binary, system server: yes
05-22 14:05:30.870 I/Xposed  ( 7652): SELinux enabled: yes, enforcing: no
05-22 14:05:33.577 I/Xposed  ( 7652): -----------------
05-22 14:05:33.577 I/Xposed  ( 7652): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
05-22 14:05:35.263 I/Xposed  ( 7652): Detected ART runtime
05-22 14:05:35.267 I/Xposed  ( 7652): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
05-22 14:05:35.488 I/Xposed  ( 7652): Loading modules from /data/app/xyz.paphonb.androidpify-xAHSBDtb7Ek_Kg69WiLe2Q==/base.apk
05-22 14:05:35.706 I/Xposed  ( 7652):   Loading class xyz.paphonb.androidpify.XposedHook
05-22 14:05:45.197 I/Xposed  ( 7978): [Android P-ify] [ERROR] : onAttachedToWindow: mIconManager = null
05-22 14:13:09.784 I/XposedInstaller(14022): Downloaded http://dl.xposed.info/repo/partial/14953.xml.gz with status 0 (error: null), size 21663 bytes
05-22 14:13:09.894 I/XposedInstaller(14022): Updated repository http://dl.xposed.info/repo/full.xml.gz to version 14981 (5 new / -1 removed modules)
```

**Comment by paphonb** [comment]
The only fix possible will require new classes that only exist on P so this is not possible. Closed for now.
