### ISSUE TITLE
Android P Recent Apps Not Showing (No recent items)

### ISSUE THREAD

**Issue by IlhamPrabaswara** [paphonb/AndroidP-ify#95]
**ROM info**
Pixel Experience (Xiaomi Mi 5)

**Module version (build version)**
Android P-ify version 1.0.0_150

**Screenshoot**
![1](https://user-images.githubusercontent.com/20736375/40427254-5ec07722-5ec7-11e8-928c-31f6ade1ac25.png)
![2](https://user-images.githubusercontent.com/20736375/40427264-628ef2ca-5ec7-11e8-8479-00ed26506bb1.png)
![3](https://user-images.githubusercontent.com/20736375/40427265-63e64240-5ec7-11e8-8875-fb66dea669d2.png)

**Comment by paphonb** [comment]
Please use the normal version of modded pixel launcher. The "for Pixel" version won't work.

**Comment by IlhamPrabaswara** [comment]
@paphonb It has pixel launcher built in so I had to install the pixel version
