### ISSUE TITLE
There was an error parsing the package (v1.0.0 150)

### ISSUE THREAD

**Issue by psydex** [paphonb/AndroidP-ify#98]
**Description**
Could not install APK on Nexus 5 running LineageOS 14.1
**There was an error parsing the package**

**ROM info**
Nexus 5 with LineageOS 14.1

**Module version (build version)**
Android P-ify version 1.0.0 150

**Xposed log / logcat**
none

**Comment by paphonb** [comment]
This module is for Android Oreo.
